// ============================================================
// LISTA DE ASSESSORES
// ============================================================
const ASSESSORES = [
  "Adyr Nicchio Neto",
  "Adriano Morandi Rondeli",
  "Alecio Bernardino da Silva",
  "Alessandra Reis Estanislau",
  "Amanda Boaventura Xavier",
  "Amanda Martins Soares",
  "Ana Carolina Gomes dos Santos",
  "Andre Pereira da Motta",
  "Andrea de Aguiar Dias Saraiva Gomes",
  "Arthur Massucatti Rondeli",
  "Athos Fontenelle Fittipaldi",
  "Bernardo Cascao Bougleux Couto",
  "Bernardo Chalub Pereira da Costa",
  "Bruno Mansur de Mello Goncalves",
  "Bruno Matosinhos Sbraletta",
  "Bruno Moraes de Caldas",
  "Bruno Thomaz Lott",
  "Caio Cesar Silva",
  "Camila Barbosa de Souza Garcia",
  "Carlos Augusto Ribeiro Lima",
  "Cristiane Gomes Pereira",
  "Daniel de Albuquerque Cola Pim",
  "Daniel Giestas Basilio",
  "Danilo de Vellasco Villela",
  "Danilo dos Santos Chaves",
  "Danilo Weslei Moraes de Souza",
  "Darlington de Paiva Bernardes",
  "Douglas Niero",
  "Durval Alaisson da Silva Vieira",
  "Eduardo de Oliveira Santos",
  "Eduardo Depes Vergara Lopes",
  "Enzo de Andrade Dorigheto",
  "Eurico Carvalho Caldas",
  "Eustaquio Mafra",
  "Everton Santos de Sousa",
  "Fabiano Pires Vieira",
  "Fabiano Werner",
  "Fabio Saraiva Barbosa",
  "Fabricio Barbosa de Lima",
  "Fabricio Vieira Lopes",
  "Felipe Borges Santos",
  "Felipe Pinheiro Sathler",
  "Felipe Thiago Dalpra Pessoa",
  "Fernando Assuncao Miranda",
  "Filippe Fioresi Sily",
  "Flavio Goncalves Maciel de Figueiredo",
  "Francisco Felipe Avilar Teixeira",
  "Gabriel Gomes Melo Carvalho",
  "Gabriel Grillo Pansiere",
  "Giancarlo Sidoti",
  "Guilherme de Assis Colossal",
  "Guilherme Margotto Gramelich",
  "Gustavo Rodrigues Coelho",
  "Gustavo Shigueru Tayamichi Sato",
  "Henrique Galvao Colares",
  "Henrique Godinho Ruoccolo",
  "Henrique Rizzi Ferreira",
  "Henrique Stancioli Tonoli",
  "Higor Rabelo da Silva",
  "Hindenburg de Alencar Barreto Coelho Neto",
  "Ian Araujo Lopes",
  "Icaro Gabriel Valentim Cruz",
  "Icaro Fortes Ventura",
  "Igor Amado Ramos",
  "Jair Rodrigues dos Santos",
  "Jhady Cerdeira de Vasconcelos",
  "Joao Goncalves Neto",
  "Joao Lucas Silveira Dutra",
  "Joao Luiz Silva Pires",
  "Joao Pedro Cordeiro Rocha",
  "Joao Pedro Gentil Goncalves da Rocha",
  "Joao Victor Musso Gomes de Souza",
  "Joao Victor Rossoni Ronchi",
  "Joao Vitor Luchi Almeida",
  "Joao Vitor Pompermayer Vettoraci",
  "Jose Eduardo Goncalves Barros",
  "Joyce Stefanni de Sousa Rolins",
  "Julia Bortolini Lima",
  "Juliana Castro David Alves de Lima",
  "Juliana Macedo Soares Nascimento",
  "Keone Reimann Kojin",
  "Konrad Campos Salomao",
  "Leonardo Borgo Machado dos Santos",
  "Leonardo Gustavo Pastore Dyna",
  "Leticia Veras Batista",
  "Lorena Maria Stein de Siqueira Varejao",
  "Lucas Andrade Felestrino",
  "Lucas Betini Motta",
  "Lucas Carvalho Guerra",
  "Lucas Deivid de Souza Miranda",
  "Lucas de Souza Soares",
  "Luis Gustavo Rodrigues",
  "Luiz Felipe Goncalves Gava",
  "Luiz Felipe Zon Werneck Guimaraes",
  "Luiz Guilherme Beltrao Barcik",
  "Luiz Henrique Faroni Bortolon",
  "Maicon Pizzol",
  "Maira Vianna de Andrade",
  "Marcelo de Moura Rosa",
  "Marcelo Messias da Silva Costa Reis",
  "Marco Antonio Solano Salmaso",
  "Marcus Araujo Alves dos Santos",
  "Mariana Emelly da Silva Quintanilha",
  "Mateus Battella de Siqueira Simoes",
  "Mateus Dias Rios",
  "Matheus Cardoso Pimentel",
  "Matheus Menezes Machado",
  "Mauro Bueno do Nascimento",
  "Mauricio Jose Viana Real de Lemos",
  "Mayron Campi Lima Barbosa",
  "Murilo Bonfim Marques",
  "Myrna Silveira de Souza Vasconcelos",
  "Natalia Moreira Zucchi",
  "Nicholas Goncalves Camara",
  "Paloma de Lavor Lopes",
  "Patricia Trigueiro da Mota",
  "Paulo Henrique Franca da Silva",
  "Pedro Aguiar Lima",
  "Pedro Augusto Silva Machado",
  "Pedro Borges Coleta Nascimento",
  "Pedro Fajardo da Cunha",
  "Pedro Henrique da Costa Silva",
  "Pedro Henrique Moutinho Campos",
  "Pedro Henrique Scaramussa Ramos",
  "Rachel Mendonca Costa",
  "Rafael Alves de Brito Oliveira",
  "Rafael Cataldo da Costa Souza",
  "Rafael Goncalves Tome",
  "Rafael Helbourn Bastos",
  "Ramon Serrao Coser",
  "Raquel Rodrigues Pires Bermond",
  "Roberto Balarini Junior",
  "Roberto Costa Pereira",
  "Roberto Uillian da Silva",
  "Romulo Nunes Goncalves",
  "Samuel Fernando Scalise Miranda Filho",
  "Samuel Merheb Vaz Pessoa",
  "Stefan Sarkis Woelffel Furtado",
  "Tamara Danielle da Silva",
  "Teodoro Aragao da Rocha",
  "Thales Nascimento de Faria",
  "Thiago Santana de Oliveira",
  "Thiago Valencia",
  "Tiago Damasceno de Barros Morgado",
  "Vanessa dos Passos Correa",
  "Victor Felipe Oliveira Souza",
  "Victor Leal Sartorio",
  "Vinicius de Moraes Mazolini",
  "Vinicius Moraes Paris de",
  "Vinicius Saldanha Soares Pinto",
  "Virgilio Alves Lourenco Lage",
  "Vitor Capeli Pereira",
  "Vitor Augusto Madeira Gomes",
  "Vitor Giacomin Pimentel",
  "Vivian Busch",
  "Vyctor Fialho Nacarati Tavares",
  "Wagner Leon Varejao",
  "Walace Silva de Souza",
  "Wesley da Silva Feitosa",
  "Willian de Angeli Prata",
  "Yago Loureiro Comerio"
];
